name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:

  build-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

        
      - name: Setup keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android/upload-keystore.jks
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=${{ github.workspace }}/android/upload-keystore.jks" >> android/key.properties


      - name: Validate keystore
        run: |
          keytool -list \
          -keystore android/upload-keystore.jks \
          -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
          -alias "${{ secrets.KEY_ALIAS }}" || exit 1

      - name: Build APK
        run: flutter build apk --release -v

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  release:
    needs: [build-android]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          generate_release_notes: true
          files: |
            android-apk/app-release.apk
